# Generated by Django 5.0.4 on 2024-04-12 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_options_alter_useraccount_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название удобства')),
                ('svg_icon', models.TextField(verbose_name='SVG код иконки удобства')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название игры')),
                ('svg_icon', models.TextField(verbose_name='SVG код иконки игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сооружения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Телефонный номер владельца')),
                ('adress', models.CharField(default='Ташкент', max_length=250, verbose_name='Адрес')),
                ('adress_url', models.URLField(default='https://yandex.uz/maps/10335/tashkent/?ll=69.279737%2C41.311151&z=12', max_length=300, verbose_name='Адрес URL')),
                ('adress_coordinates', models.CharField(default='41.311151, 69.279716', max_length=50, verbose_name='Кординаты адреса поля')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('start_time', models.TimeField(verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(verbose_name='Конец рабочего дня')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.game', verbose_name='Вид сооружения')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounts.region', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Сооружения',
                'verbose_name_plural': 'Сооружения',
                'ordering': ['-created_at', 'region'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название или номер кабинета')),
                ('price', models.IntegerField(verbose_name='Цена сооружения на час')),
                ('image', models.ImageField(default='field-default.jpg', upload_to='facility/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(null=True)),
                ('benefits', models.ManyToManyField(to='accounts.benefit', verbose_name='Удобство сооружения')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.facility', verbose_name='Название сооружения')),
            ],
        ),
    ]
