# Generated by Django 5.0.4 on 2024-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_benefit_game_region_facility_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='svg_icon',
        ),
        migrations.AddField(
            model_name='game',
            name='svg_icon_colored',
            field=models.TextField(default='', verbose_name='Цветной SVG код иконки игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='svg_icon_non_colored',
            field=models.TextField(default='', verbose_name='Нецветной SVG код иконки игры'),
        ),
    ]
