# Generated by Django 5.0.4 on 2024-04-12 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_game_svg_icon_game_svg_icon_colored_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.AddField(
            model_name='facility',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
