# Generated by Django 5.0.4 on 2024-04-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_facility_slug_remove_room_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
