# Generated by Django 5.0.4 on 2024-04-12 13:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_facility_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
