# Generated by Django 5.0.4 on 2024-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_facility_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='facilities'),
        ),
    ]
