# Generated by Django 5.0.4 on 2024-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_facility_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='adress_coordinates',
            new_name='address_coordinates',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='adress_url',
            new_name='address_url',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='adress',
        ),
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.CharField(default='Ташкент', max_length=250, verbose_name='Адрес сооружения'),
        ),
    ]
