# Generated by Django 5.0.4 on 2024-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата бронирования'),
        ),
    ]
