# Generated by Django 5.0.4 on 2024-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notification_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Владелец сооружения'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('excluded', 'Excluded')], default='pending', max_length=10),
        ),
    ]
