# Generated by Django 5.0.4 on 2024-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_useraccount_is_owner_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название игры'),
        ),
    ]
