# Generated by Django 5.0.4 on 2024-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_game_title_ru_game_title_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название района'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название района'),
        ),
    ]
