# Generated by Django 5.0.4 on 2024-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_region_title_ru_region_title_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название удобства'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название удобства'),
        ),
    ]
