# Generated by Django 5.0.4 on 2024-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_benefit_title_ru_benefit_title_uz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['pk'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_uz',
            field=models.TextField(null=True),
        ),
    ]
