# Generated by Django 5.0.4 on 2024-05-29 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_notification_options_notification_message_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('deposit', 'Депозит'), ('full', 'Полная оплата')], default='full', max_length=20)),
                ('total_price', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата бронирования')),
                ('time', models.JSONField(blank=True, default=list, verbose_name='Время бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.room', verbose_name='Название комнаты')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordering_as_user', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
