# Generated by Django 5.0.4 on 2024-05-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_rename_id_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
