# Generated by Django 5.0.4 on 2024-05-30 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rename_order_id_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='order_as_invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенные пользователи'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='bookings_as_invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенные пользователи'),
        ),
    ]
