# Generated by Django 5.0.4 on 2024-05-30 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_order_invited_users_alter_booking_invited_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='invited_users',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='booking',
        ),
        migrations.AddField(
            model_name='invitation',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.order'),
        ),
    ]
