# Generated by Django 5.0.4 on 2024-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_booking_invited_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payme_checkout_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссыслка дл оплаты через Payme'),
        ),
    ]
