# Generated by Django 5.0.4 on 2024-06-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_order_payme_checkout_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
