# Generated by Django 5.0.4 on 2024-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_useraccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=12, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
