# Generated by Django 5.0.4 on 2024-06-10 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен состоять из 12 цифр', regex='^\\d{1,12}$')], verbose_name='Номер телефона'),
        ),
    ]
