# Generated by Django 5.0.4 on 2024-06-24 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payme_checkout_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссыслка для оплаты через Payme'),
        ),
    ]
