# Generated by Django 5.0.4 on 2024-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_order_order_uuid_alter_order_payme_checkout_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
