# Generated by Django 5.0.4 on 2024-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_useraccount_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='favorite_sports',
            field=models.JSONField(blank=True, default=list, verbose_name='Любимые виды спорта'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='kind_of_activity',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Логотип'),
        ),
    ]
