# Generated by Django 5.0.4 on 2024-07-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_useraccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='kind_of_activity',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='free_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Свободное время'),
        ),
    ]
