# Generated by Django 5.0.4 on 2024-07-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_useraccount_kind_of_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='home_address',
        ),
    ]
