# Generated by Django 5.0.4 on 2024-07-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_useraccount_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favorite_sports',
            field=models.JSONField(blank=True, default=list, verbose_name='Любимые виды спорта'),
        ),
    ]
